# Generated by Django 4.2 on 2023-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
    ]
