# Generated by Django 4.2 on 2023-05-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_foto_alter_post_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, max_length=200, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
